### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by chripede** [TrackMaven/celery-once#18]
When one of the parameters is not an ascii character this happens:

```
Task x[42ce145b-9364-4961-b9ea-12cd192aa49c] raised unexpected: UnicodeDecodeError('ascii', 'l\xc3\xa5n', 8, 9, 'ordinal not in range(128)')
...
 line 76, in queue_once_key
    key = "_".join(keys)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 8: ordinal not in range(128)
```

Python 2.7

**Comment by cameronmaske** [comment]
@chripede Which version of celery once are you on? 0.1.1 includes some unicode fixes (#11). 
If you are on 0.1.1, could you include an example of running .delay with arguments thats creates the error?

**Comment by chripede** [comment]
@cameronmaske I'm using 0.1.1.
My call do .delay is like this `.delay(model, stats_date=date_var)`
Where model has a __unicode__ that seems to be the one used for the key.

This commit https://github.com/chripede/celery-once/commit/c7335256d06a96579b2250d0e619da17b7f67da3 fixes the error, but it breaks Python 3 compatibility.

**Comment by cameronmaske** [comment]
@chripede Do you happen to override the name of your celery task? e.g.
```
@celery.task(name=u"foo")
def foo(a, b, c):
    pass
```

The UnicodeDecodeError should only be raised if attempting to join unicode and string objects and #11 should force everything but the name to a string.

**Comment by chripede** [comment]
@cameronmaske I am overriding the name like this `name="custom.name"` not using unicode.

**Comment by cameronmaske** [comment]
@chripede #20 should hopefully fix this! Let me know if it doesn't and we can re-open this.
