### ISSUE TITLE
Key collisions

### ISSUE THREAD

**Issue by chripede** [TrackMaven/celery-once#19]
When sending Django models as args to tasks, part of the key is generated by converting the model to a string. This causes key collisions for us since we have multiple objects that outputs the same from `__unicode__`

I propose something like this https://github.com/chripede/celery-once/commit/a2b465ce8fd1aa6593cfb5bfe7712320e792bf5f to allow objects to create unique keys.

The code in my django model would look something like this
```
    def __unicode__(self):
        return self.domain

    def celery_once_key(self):
        return "{}-{}".format(self.pk, self.domain)
```

**Comment by cameronmaske** [comment]
@chripede Hey, thanks for the feature suggestion! 
One way to achieve this with the current version of celery once is too pass UUID as an argument of the task, and limit celery once to look at that key, e.g. like...

e.g.
```
@tasks(base=QueueOnce, once={'key': ['pk']})
def example(model, pk):
  pass
```

I'm not sure how I feel about a custom method on objects. Celery tends to [err away from passing around models](http://celery.readthedocs.org/en/latest/userguide/tasks.html#state). 
For that reason, I'm hesitate to support this, unless others out there would really find it useful? I'm gonna close this out for now, but happy to revisit it, if it has others support.

**Comment by chripede** [comment]
@cameronmaske while they tend to err away from it, they still allow it. Everyone has a different use case.

Anyways, I'll add a bogus parameter to my task to keep the keys unique.

**Comment by Skyross** [comment]
Why not to use `self.request.id` for that purpose?
