### ISSUE TITLE
Is there any way to queue a task instead or rejecting it?

### ISSUE THREAD

**Issue by danechitoaie** [TrackMaven/celery-once#26]
From what I see in the documentation now if I try to queue same task twice I will get an exception "AlreadyQueued()"

Is there any way that the task is still queued but doesn't actually start until the previous one (with same key) is finished instead of just dropping it?

**Comment by cameronmaske** [comment]
@danechitoaie This isn't currently possible with `celery_once`. 
If you wanted a lock that didn't allow two of the same tasks running at the same time, but both while both being queued, you could maybe achieve it by activating the lock inside the `__call__` (or task) and having it retry later on if the another task is running.

**Comment by danechitoaie** [comment]
Hi,

Yes, I ended up doing something like:

```python
    task_lock = util.RedisLock(redis.StrictRedis.from_url(config.URL_CELERY_LOCK), lock_key, lock_val)

    # Acquire the lock or retry the task in 3m
    if not task_lock.acquire():
        raise self.retry(countdown=180)
```

and util.py

```python
class RedisLock(object):
    def __init__(self, redis, lock_key, lock_val):
        super(RedisLock, self).__init__()
        self.redis    = redis
        self.lock_key = "lock:{0}".format(lock_key)
        self.lock_val = "task:{0}".format(lock_val)

    def acquire(self):
        lock_key = self.lock_key
        lock_val = self.lock_val

        return self.redis.set(lock_key, lock_val, ex=3600, nx=True)

    def release(self):
        lock_key = self.lock_key
        lock_val = self.lock_val

        def execute_release(pipe):
            if pipe.get(lock_key) == lock_val:
                pipe.delete(lock_key)

        self.redis.transaction(execute_release, lock_key)

```

**Comment by cameronmaske** [comment]
Great! Thanks for sharing the code. 
Gonna close this issue out.

**Comment by jperelli** [comment]
This should go into documentation!
